{{- if .Values.datasources.enabled }}
{{- range $sources := .Values.datasources.sources }}
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ $sources.name }}
  namespace: kubevirt
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"

spec:
  source:
    http:
      url: "{{ $sources.url }}"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: {{ $sources.storage }}
{{ end }}
{{- end }}
